### ISSUE TITLE
When I close the application it doesn't open again[BUG]

### ISSUE THREAD

**Issue by OnlyIssues** [Davidobot/BetterJoy#1002]
So I decided to close the application, since I went straight to the emulator I used, then I decided to split the joy cons, but the app says "Application is already open" or something. I even tryed going to task manager, it wasn't there.

I thought the app would just open and I would split the joy cons, but it didn't!

Controller:
 - Type: split joy-cons
 - Connection: bluetooth

**Comment by OnlyIssues** [comment]
Guys, I can't reboot the PC each time I just want to change something!

**Comment by OnlyIssues** [comment]
If I don't get something, and it isn't a bug, I shhould get help too, right?

**Comment by neopilou** [comment]
You don't need to reboot every time, just kill the app via task manager. When you close or minimize the app, it doesn't appear in the notification area, but it's still running in the background...

**Comment by neopilou** [comment]
It seems to come from the .net framework 4.6.1 used to develop the application, with 4.8, the problem is no longer present.

**Comment by OnlyIssues** [comment]
Bruh Thank you I al
