### ISSUE TITLE
[PROBLEM] Connected, but not showing in the BetterJoy

### ISSUE THREAD

**Issue by P1upp3t** [Davidobot/BetterJoy#1008]
![image](https://user-images.githubusercontent.com/110955308/183800954-4b1642b4-03c7-451d-a997-2f8d8e9519a4.png)

**Comment by P1upp3t** [comment]
Now it's crashing

**Comment by P1upp3t** [comment]
i'm trying to use the Yuzu

**Comment by P1upp3t** [comment]
![image](https://user-images.githubusercontent.com/110955308/183805996-9c1aa6a4-ee81-41bc-bf40-55ec2c0a68aa.png)

**Comment by P1upp3t** [comment]
![image](https://user-images.githubusercontent.com/110955308/184022986-89973d74-ce98-4f0e-94a9-83ce012bc430.png)
Today it's been the same.

**Comment by Hgamer999** [comment]
Hey Bro, did you get this to work? I am having the exact same issue as you. First it was giving me the duplicate time stamp enqueued error but after uninstalling and reinstalling now it won't see them at all. Did you manage to fix this? Thanks!

**Comment by WictorDalbosco** [comment]
Same here guys, did you find any solution??
