### ISSUE TITLE
[ENHANCEMENT] PXN 9607X Controller support?

### ISSUE THREAD

**Issue by Zyga21** [Davidobot/BetterJoy#1103]
Hey I saw this thread https://github.com/Davidobot/BetterJoy/issues/419 and was hoping you'd add support for the controller I have too ( https://www.amazon.com/dp/B09SW4ZFPQ ) , I followed the same steps so that maybe I could save you time with it? The gyro and everything functions on the switch, and if a game is running through steam and supports gyro it also supports it, but for some reason it acts like an xbox 360 controller otherwise and is never seen by betterjoy.

```
HidGuardian is enabled.
Starting server on 127.0.0.1:26760
-- COPY ME --
Name: Controller (XBOX 360 For Windows) Vendor: 1118 Product: 654
-- COPY ME END --
All systems go
```

would be willing to go through any debugging necessary because I'm too broke to afford another switch controller that does have gyro working innately, and I really want to use the gyro this controller has.

also if you use discord and want faster responses; im on there as Zyga (new username type without discrim numbers)

**Comment by Zyga21** [comment]
also it strangely shows up in http://localhost:26762/ (HID configuration) as 
```
ZhiXu Gamepad
HID\VID_0079&PID_181C
```
or in BetterJoy_Test_Ver's dialog box as
```
Name: Gamepad Vendor: 121 Product: 6172
``` 

but if I disconnect/reconnect it it changes to 
```
Unknown Controller (XBOX 360 For Windows)
HID\VID_045E&PID_028E&IG_00
```
and
```
Name: Controller (XBOX 360 For Windows) Vendor: 1118 Product: 654
```

**Comment by Mp3File** [comment]
i know im late to this but how did you get the gyroscope working on steam

**Comment by Zyga21** [comment]
it worked by default, but if you have it connected via cable ever it will always act like a 360 controller and take away any of the extra functions, you have to use it as a bluetooth controller. 

Also somewhere along the line the dev added this controller and it works with betterjoy, thank you ^^

**Comment by Mp3File** [comment]
but how did bluetooth work though i dont understand at the moment cause im
guessing im suppose to charge it but i dont know how to do that also thanks
for the response

**Comment by Zyga21** [comment]
well, if you have bluetooth on your computer and you search for it, just connect it. idk what you mean

to charge the controller just plug it into anything, it charges even while being used wired

**Comment by Mp3File** [comment]
ill try and look around its just that i bought it and when i connected it
to steam it worked but the gyro didnt

**Comment by Mp3File** [comment]
i managed to get it working thanks

**Comment by aminkoli** [comment]
> i managed to get it working thanks
> […](#)

Can you tell Me how you managed to get it working, I have the same problem

**Comment by Mp3File** [comment]
use it bluetooth not cable, press the middle of the dpad or some some other
buttons to turn it on and make sure its not plugged
