### ISSUE TITLE
NOT A BUG BUT TO UNINSTALL I NOW HAVE BEEN LITERALLY FORCED TO REINSTALL WINDOWS!!!!

### ISSUE THREAD

**Issue by AlexLT1** [Davidobot/BetterJoy#1126]
I went to uninstall 7.1, and found no uninstaller. I decided to just delete everything and it wouldn't let me. I found the file and as of why, so I tried to delete the service that this software required. I ensured in my search filter that I had chosen NON WINDOWS, as to prevent me from choosing something that would cause an issue. It wouldn't let me. Only allowed me to stop it, not delete it. I found a method with another application that I had, which actually allowed me to delete the initial thing I was trying to do so, and upon doing so and restarting my computer, I literally cannot get it to boot anymore. I am now forced to reinstall windows as I've tried for about 20 minutes thinking something went wrong. The input devices I have connected do not stay connected as well. 

This absolutely needs to be addressed, as it was not useful for me and as a consequence I have to reinstall absolutely everything I had all over again.

**Comment by AlexLT1** [comment]
Lucky bastard. I had finally booted into bios and got windows to repair mode, which I was able to finally restore back. I had one restore point so I'm glad, but damn if I ever install this shit ever again on a new computer

**Comment by YoraeRasante** [comment]
So... basically you wanted to get rid of this because you would not use it anymore, and in this you ended up trying to delete something it _uses_ instead? And when your Windows refused to let you delete it, instead of trying to find out why you looked online for something that would let you do so instead of looking for what it is?
Seems to me like the reason you had to reinstall Windows was this second program you used that let you erase what you should not, not BetterJoy.
(and honestly, as far as I knew the method to uninstall BetterJoy was "erase the BetterJoy folder without BetterJoy itself running")

But out of curiosity, what DID you try to delete so much, and what program did you use to do it?

...wait, how do you set a search filter for "non windows"? I'm pretty sure things are spread among multiple folders so...

**Comment by AlexLT1** [comment]
> So... basically you wanted to get rid of this because you would not use it anymore, and in this you ended up trying to delete something it _uses_ instead? And when your Windows refused to let you delete it, instead of trying to find out why you looked online for something that would let you do so instead of looking for what it is?
> 
> Seems to me like the reason you had to reinstall Windows was this second program you used that let you erase what you should not, not BetterJoy.
> 
> (and honestly, as far as I knew the method to uninstall BetterJoy was "erase the BetterJoy folder without BetterJoy itself running")
> 
> 
> 
> But out of curiosity, what DID you try to delete so much, and what program did you use to do it?
> 
> 
> 
> ...wait, how do you set a search filter for "non windows"? I'm pretty sure things are spread among multiple folders so...

There was a button for it. I searched for hours. I heard reports of a batch file, but then reports of it not working. I found reports of using a service called lock Hunter, it didn't work. I heard reports that you can just uninstall everything in steps, that also did not work. I actually finally found the batch file myself, as it was hidden within folders and I didn't expect it to be which is my fault, but it also did not work. I am not the most tech savvy, so when nothing works to get this to stop, the logical step for me is to delete the things that require it to work that are not core files associated with computer functionality, yet it somehow did anyway, but as I said I fixed it. I still cannot get this to uninstall, over and over and over again I've tried. It's the equivalent of parasite in my eyes. A software which won't go away despite running the uninstalled and it saying "it's uninstalled" it still is affecting my hardware. Trash software through and through

**Comment by AlexLT1** [comment]
All I want is the software to stop affecting my controller. I've deleted the folder without anything running and it still is affecting my controller. I cannot get it to stop. Since it's emulating keyboard it does not show up as a new device under windows devices you have connected, and I can't find out which one it is in the device manager as they're all listed as the same thing with no difference. If it doesn't then it fucked my pro controller, which is fan fucking tastic.> > So... basically you wanted to get rid of this because you would not use it anymore, and in this you ended up trying to delete something it _uses_ instead? And when your Windows refused to let you delete it, instead of trying to find out why you looked online for something that would let you do so instead of looking for what it is?
> > 
> > Seems to me like the reason you had to reinstall Windows was this second program you used that let you erase what you should not, not BetterJoy.
> > 
> > (and honestly, as far as I knew the method to uninstall BetterJoy was "erase the BetterJoy folder without BetterJoy itself running")
> > 
> > 
> > 
> > But out of curiosity, what DID you try to delete so much, and what program did you use to do it?
> > 
> > 
> > 
> > ...wait, how do you set a search filter for "non windows"? I'm pretty sure things are spread among multiple folders so...
> 
> There was a button for it. I searched for hours. I heard reports of a batch file, but then reports of it not working. I found reports of using a service called lock Hunter, it didn't work. I heard reports that you can just uninstall everything in steps, that also did not work. I actually finally found the batch file myself, as it was hidden within folders and I didn't expect it to be which is my fault, but it also did not work. I am not the most tech savvy, so when nothing works to get this to stop, the logical step for me is to delete the things that require it to work that are not core files associated with computer functionality, yet it somehow did anyway, but as I said I fixed it. I still cannot get this to uninstall, over and over and over again I've tried. It's the equivalent of parasite in my eyes. A software which won't go away despite running the uninstalled and it saying "it's uninstalled" it still is affecting my hardware. Trash software through and through

**Comment by AlexLT1** [comment]
> So... basically you wanted to get rid of this because you would not use it anymore, and in this you ended up trying to delete something it _uses_ instead? And when your Windows refused to let you delete it, instead of trying to find out why you looked online for something that would let you do so instead of looking for what it is?
> 
> Seems to me like the reason you had to reinstall Windows was this second program you used that let you erase what you should not, not BetterJoy.
> 
> (and honestly, as far as I knew the method to uninstall BetterJoy was "erase the BetterJoy folder without BetterJoy itself running")
> 
> 
> 
> But out of curiosity, what DID you try to delete so much, and what program did you use to do it?
> 
> 
> 
> ...wait, how do you set a search filter for "non windows"? I'm pretty sure things are spread among multiple folders so...

Just uninstalled everything exactly as you said. My controller is not working in dolphin. What do I do since you have the answers apparently that no one online does, and I need this fixed. I hate this software so much man it broke everything for me
