### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by higarbagexd** [Davidobot/BetterJoy#1134]
**Describe the bug**
Hi, I have a 3rd Party Switch Pro Controller   ( Gulikit KingKong 2 Pro Controller) (https://www.gulikit.com/productinfo/737791.html)
I have been trying to use BetterJoy for Yuzu and im using 1 pro controller, i use the add controller tab [ it shows up as HIDI2C Device(1267-12541-9999) ]
and once i set the type to pro controller, betterjoy shows 4 pro controllers on the other window, and on the console it shows :

-start
Pro Controller connected.
Starting poll thread.
Dropped.
Removed dropped controller. Can be reconnected.
-end

it loops the same thing unless i set it from " Switch Controllers" to "All devices" , where then no controllers are shown.

i have checked #419 and the solutions from there do not seem to work. 

**Expected behavior**
One controller to appear on **Connected Controllers**, and on the console 
" Pro Controller Connected 
Starting poll thread "

**Controller:**
 - Type: [Pro Controller]
 - 3rd party
 - Connection: [USB]
![Screenshot 2023-10-27 174752](https://github.com/Davidobot/BetterJoy/assets/149179584/6f73e657-120f-410b-9de5-08216e55d294)
![Screenshot 2023-10-27 175538](https://github.com/Davidobot/BetterJoy/assets/149179584/3f055d36-cfc7-423c-aba0-645f000ccf60)

**Comment by CreeperSword** [comment]
having a switch in proximity can mess with betterjoy, make sure to unpair it from your switch if you have one nearby
