### ISSUE TITLE
[ENHANCEMENT] Add a feature that allows you to pair controllers through betterjoy and it bypasses pins

### ISSUE THREAD

**Issue by Minecraftplayer20** [Davidobot/BetterJoy#1156]
I want a feature that makes it so you can pair controllers through betterjoy and it can bypass entering the pin.

**Comment by cercatore** [comment]
what the fuck do you think your are fucker?

**Comment by Minecraftplayer20** [comment]
> you are A NULL and you r supposed to ASK, the work is made by people here you sick fuck

fuck you your moms a hoe
