### ISSUE TITLE
Better Joy by default is making my joycons act like a mouse and i can't disable it from doing that[BUG]

### ISSUE THREAD

**Issue by CodeRiverFoxLife** [Davidobot/BetterJoy#1166]
Today, BetterJoy suddenly thought to make my joycons stick inputs into mouse movement in certain apps.

I have no idea what is causing it. Someone please help. This has never happened before. This is a new copy of windows 10 and i just installed betterjoy for this to happen

**Comment by Lucyfurnice** [comment]
do you have steam open?

**Comment by CodeRiverFoxLife** [comment]
No. But the issue fixed itself today. For some reason, it only happens in one app, so I made an edit to it and it stopped. Thanks though.
