### ISSUE TITLE
Any chance of getting it working on linux (in wine)?

### ISSUE THREAD

**Issue by v1993** [Davidobot/BetterJoy#159]
AFAIK, there is some kind of support for stuff like this in wine and WiiHook can be used on linux with some minor tweaking.

Is it possible to do the same with BetterJoyForCemu? Did anybody actually tried that?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
just use Joycond and joycond-cemuhook

**Comment by Heath123** [comment]
Does that have gyro support though?

**Comment by v1993** [comment]
> Does that have gyro support though?

Yes, even tho I wrote my own solution that doesn't require usage of cemuhook. Technically, you need dkms-hid-nintendo for gyro support in either case.

Since I've solved this issue, I'm closing it now.

**Comment by Heath123** [comment]
By the way I mean gyro pointer support, not just normal gyro (I can't see any mention of it but maybe it does)

**Comment by v1993** [comment]
@Heath123 I think if it is ever one by someone, it should be done in form of DSU client, compatible with all possible DSU servers, saving all DSU server writers from unnecessary work.

**Comment by Heath123** [comment]
That would probably make sense if it's doing mouse emulation
