### ISSUE TITLE
NonOriginalController fixes gyro but breaks stick ranges

### ISSUE THREAD

**Issue by clawyf** [Davidobot/BetterJoy#192]
On my Switch Pro controller, I sometimes experience gyro drift to the left. When I enable the setting that allows for gyro calibration, it goes away completely at the cost of neither analog stick being able to reach its full value. It makes it impossible to run or turn the camera at a normal speed.

**Comment by xqdoo00o** [comment]
if change the setting,you need restart all soft(first start this, then you app cemu or what, keep that order)
