### ISSUE TITLE
Cannot Recognize that Controller Exists

### ISSUE THREAD

**Issue by akkifireborker** [Davidobot/BetterJoy#196]
I am currently using v6 Nightly 7, but this issue occurs on all versions I've tested so far (including v3, v4, v5)

Plugging in the USB Pro Controller does absolutely nothing with BetterJoyForCemu. My Windows 10 Home recognizes it as Core (Plus) Wired Controller but beyond that, absolutely nothing. Passive Scan is toggled on, and I've followed all the advice I've been given, including removing all devices from the "Currently Affected Devices" list of http://localhost:26762/ (there were none there by default), and doing the suggested method of going into Device Manager and toggling off the ability disable USB ports to save power. As I mentioned above I've tested with a few different versions, restarting my computer after each change. I've uninstalled and reinstalled the drivers for BetterJoyForCemu as well as the drivers for vJoy and the default ones that come when I initially plug in the controller. Nothing has worked, and I'm genuinely quite confused. 

Hitting the "Add Controllers" button that comes with the Nightly version I'm using just pops up with an error: 
> Unhandled exception has occurred in your application. Cannot perform runtime binding on a null reference.

There is a details button in the dialogue box that pops up, which clicking on reveals a lot of code I don't understand. I would be happy to copy paste, but only if whoever thinks they can help says it's necessary. I don't understand much code talk, maybe I'm just overlooking something obvious, but I just want to get to play some video games, and would really appreciate any help anyone can give.

**Comment by v5tge** [comment]
Im not sure 100% but i think you need to connect the controller with Bluetooth the first time you use it. Then you can use the usb cable.

**Comment by akkifireborker** [comment]
Ahh, that could certainly be a problem, as the Pro Controller I have is the PowerA produced variant, which is USB only. It doesn’t have Bluetooth capabilities.

**Comment by v5tge** [comment]
In that case I can't help. Mine is official switch pro controller

**Comment by akkifireborker** [comment]
It is official, PowerA produces it but Nintendo sells it on their own website as official. But, if BetterJoyForCemu isn’t compatible with it, I’ll try to find something that is. Thank you!

**Comment by NexusTheBrony** [comment]
in case this issue is somehow unconfirmed, I'm having the same issue. I got a PowerA pro controller hoping it would work with BetterJoy. obviously me posting here means it didn't

**Comment by akkifireborker** [comment]
It is, unfortunately, confirmed, BetterJoy does not work with PowerA controllers. However, there is another program that does. XOutput. It does essentially the same thing as BetterJoy, but instead of focusing on Nintendo's software, it works with stuff that Windows reads as a generic controller. BetterJoy works with JoyCons and the Wireless Pro Controllers, XOutput works with the PowerA wired-only controllers.

**Comment by NexusTheBrony** [comment]
x360ce also works with the pro controller (or any controller, including xbox controllers) and apparently is supposed to work with the joycons as well, but can't get that working

**Comment by HughDaniels** [comment]
> In that case I can't help. Mine is official switch pro controller

I use a gyro enabled honson switch pro controller. won't let me add it no matter what i do. i need it to be that one for the turbo button (rapid fire)

**Comment by NexusTheBrony** [comment]
issue persists for PowerA controllers

**Comment by akkifireborker** [comment]
> issue persists for PowerA controllers

To my understanding, there are no plans to make BetterJoy work with PowerA controllers. As I said earlier though, XOutput works perfectly well with them.
