### ISSUE TITLE
joycon and D-pad move at lighting speed

### ISSUE THREAD

**Issue by Shuaiouke** [Davidobot/BetterJoy#202]
I play BOTW in 144hz and when I hold D-Pad to switch weapon, it flys through in seconds, what's wrong here

**Comment by KurtYilmaz** [comment]
Is it normal when you play on 60Hz? The weapon hot-swapping may be tied to the framerate.

**Comment by Shuaiouke** [comment]
You're right, Im gonna try that out, but what if it IS, i dont want to play at 60hz on a 144hz monitor

**Comment by KurtYilmaz** [comment]
Are you using a wired or bluetooth connection?

**Comment by Shuaiouke** [comment]
Ive tried both wire AND bluetooth, but bjfc dont initialize correctly when wired, I also tried connecting it to my phone and streamlink it, it doesnt work either
