### ISSUE TITLE
Controller was not being detected (3rd party) and now can't install.

### ISSUE THREAD

**Issue by CDZoro** [Davidobot/BetterJoy#233]
At first I could install BetterJoyForCemu but my controller wouldn't be detected. Tried BT and USB. It is a 3rd Party Pro-Controller that pretty much is the Original but without NFC or HD Rumble, even the Nintendo Switch detects it as an original one. The option of "Add controller" doesn't seem to work as nothing happens when I click apply. I uninstalled everything and tried reinstalling it but now this shows up even if I run the .bat as admin

Installing the ViGEm emulated gamepads driver..
Installation failed; you need to right click the .bat and "run as admin".
Press any key to continue . . .

Any help would be appreciated

**Comment by SmokePuddingEveryday** [comment]
Nearly all third party controllers aren't supported with BJFC atm, nor does the Add Controllers button do anything atm.

Your third party controller should work fine in Steam Big Picture, though

**Comment by spirosmesa** [comment]
Don't you think that this should be something that should be include in the repo's description? That would save him and me a lot of trouble. This is an amazing project, is a shame to get disappointed by small stuff like that.
