### ISSUE TITLE
Rumble Causes All Bluetooth Devices To Stutter and Lag

### ISSUE THREAD

**Issue by HomelessSandwich** [Davidobot/BetterJoy#316]
I am running Windows 10, using ver. 6 of BeterJoy and use a Nintendo Pro Controller.

With rumble enabled, whenever the controller is rumbled, it causes all bluetooth devices to lag and stutter. It causes the controller to have a good 2-3sec delay along with the sounds of my bluetooth headphones to stutter for the same length of time.

Turning off rumble fixes all the above issues. Please find below the config file that I use, which causes the issues.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
  <appSettings>
    <add key="IP" value="127.0.0.1" />
    <add key="Port" value="26760" />
    <add key="MotionServer" value="true" />
    <add key="RumblePeriod" value="300" />
    <add key="LowFreqRumble" value="20" />
    <add key="HighFreqRumble" value="400" />
    <add key="EnableRumble" value="true" />
    <add key="SwapAB" value="true" />
    <add key="SwapXY" value="true" />
    <add key="PurgeWhitelist" value="true" />
    <add key="UseHIDG" value="false" />
    <add key="ShowAsXInput" value="true" />
    <add key="PurgeAffectedDevices" value="true" />
    <add key="NonOriginalController" value="false" />
    <add key="HomeLEDOn" value="true" />
    <add key="GyroToJoyOrMouse" value="none" />
    <add key="GyroMouseSensitivity" value="50" />
    <add key="GyroMouseLeftHanded" value="false" />
  </appSettings>
</configuration>
```

Here are my settings.
```
ProgressiveScan 1
StartInTray 0
capture key_44
home 0
sl_l 0
sl_r 0
sr_l 0
sr_r 0
reset_mouse joy_10
0,0,0,0,-710,0,0
```

**Comment by Toomoch** [comment]
Same issue.

**Comment by rsilva48** [comment]
Same here using USB as well, also found that lag can be reduced rising the priority of the process

**Comment by FlaminSarge** [comment]
Check if https://github.com/Davidobot/BetterJoy/issues/266#issuecomment-610471126 fixes it

**Comment by HomelessSandwich** [comment]
> Check if [#266 (comment)](https://github.com/Davidobot/BetterJoy/issues/266#issuecomment-610471126) fixes it

That seems to fix the issues. Thank you for the reply.
