### ISSUE TITLE
Analogue Stick Issues

### ISSUE THREAD

**Issue by Rug03** [Davidobot/BetterJoy#346]
I've been trying to use the plugin for a pro controller on Project64. The buttons seem to work correctly, but the left analogue stick is inconsistent. It works in certain menus, but when given a full range of motion it won't input any direction. I'm don't know a lot about this software or how it works, so please let me know if there's some fix I'm missing.

**Comment by RobertBorg** [comment]
using this configuration it seemed to work without issues for me. If this does not work for you i need you to be more specific about what dosen't work 
![image](https://user-images.githubusercontent.com/1288566/82113044-10505000-9753-11ea-9a52-8b907d6cd9ea.png)
