### ISSUE TITLE
Suggestion; Name change of the emulation software

### ISSUE THREAD

**Issue by B1G11** [Davidobot/BetterJoy#373]
Name change so that the software can be found and sound better.

My suggestions:

xJOY-CON   JOYxCON   JOY2CON   JOY][CON 
JOY2WiN   JOY][WiN   JC4Windows   ...............

Just a suggestion and thanks for the great emulation software.

**Comment by TheZBlock** [comment]
I fail to see how any of those sound or look better, to be honest.
