### ISSUE TITLE
Batch BetterJoy with Cemu 

### ISSUE THREAD

**Issue by shtiffee** [Davidobot/BetterJoy#375]
Hello

I am creating a batch file to run Cemu and BetterJoy simultaneously. 

I have this written:

echo off

start /realtime "D:\cemu_1.19.0\cemu.exe" -g "D:\Wii U Games\The Legend of Zelda Breath of the Wild [ALZP01]\code\U-King.rpx" -f"
start /realtime "D:\BetterJoy\BetterJoyForCemu.exe"

exit

*--- I am running into this issue:  BetterJoy is only running after I close Cemu.  Any suggestions are greatly appreciated.  Thank you.

**Comment by Icing-weaponry** [comment]
I also use a batch file to launch both, here's what works for me

@start "" ".\Cemu.exe"
@start "" ".\BetterJoy_v6.2_x64\BetterJoyForCemu.exe"

the batch file is located in the cemu folder and I have a shortcut made to launch for "classic start menu"

hope this helps!

**Comment by TheZBlock** [comment]
Running everything with realtime priority is a really bad idea, just so you know.

**Comment by shtiffee** [comment]
Thank you @Icing-weaponry and @TheZBlock.  I did realize that it may affect my performance and stability to run them at /realtime.  Another user on a different forum suggested it so it takes a higher priority.
