### ISSUE TITLE
Program window dissapears

### ISSUE THREAD

**Issue by DPS100** [Davidobot/BetterJoy#381]
When I minimize the application window the window itself disappears but the program continues to run, and I cannot reopen the program with the .exe, however the program is not open in taskbar but is visible in task manager.
![Screenshot (38)](https://user-images.githubusercontent.com/47835681/82834984-f19f3700-9e7f-11ea-83b6-9296f590f7c1.png)
![Screenshot (39)](https://user-images.githubusercontent.com/47835681/82834986-f2d06400-9e7f-11ea-9216-2e3154d1cda7.png)
![Screenshot (40)](https://user-images.githubusercontent.com/47835681/82834987-f2d06400-9e7f-11ea-9bc1-c507220c92e3.png)
![Screenshot (41)](https://user-images.githubusercontent.com/47835681/82834988-f2d06400-9e7f-11ea-844f-e50590137ba2.png)

**Comment by AffanKhurram** [comment]
When you minimize the program, it goes in to the system tray. Click on the arrow on the right side of the task bar and double click the icon there
