### ISSUE TITLE
[BUG] Betterjoy server not appearing as DSUClient to Cemu

### ISSUE THREAD

**Issue by Crinfarr** [Davidobot/BetterJoy#470]
**Describe the bug**
using custom port 19287 on both Cemu's end and betterjoy's, cemu does not see controllers as connected or selectable.

**Expected behavior**
Pro controller should appear as an input/motion source.

**Controller (please complete the following information):**
 - Type: Pro controller
 - Connection: bluetooth

![image](https://user-images.githubusercontent.com/31548109/89130897-9ec0ac00-d4ce-11ea-95d2-49962b16f156.png)
![image](https://user-images.githubusercontent.com/31548109/89130907-a97b4100-d4ce-11ea-92dc-ce9782fb2acf.png)

**Comment by Kgta66** [comment]
Hi Crinfarr, first of all, Cemuhook is required for Cemu to recognise Betterjoy DSU client, if its not present you need to download cemuhook, add it to your cemu folder and afeter that enter the cemuhook.ini file, there you need to specify the server IP address, in your case 127.0.0.1 , later in Cemu you can salect in options, gamepad motion source the DSU1 controller, and then when you search it on imput settings on controller it should appear as client 1. Hope it helps

**Comment by Crinfarr** [comment]
you... you literally just described exactly what I already did.  my problem is that betterjoy isn't appearing as a dsu.  I have correctly configured both cemuhook and betterjoy.

**Comment by Kgta66** [comment]
does your dsu client show when testing it using PadTest? I remember having trouble with this and my issue was that i had different IPs in the cemuhook.ini file, also try making a test with PadTest and in case you get nothing, just try the default port for DSU Client
