### ISSUE TITLE
[BUG] Controller immediately disconnects upon connecting

### ISSUE THREAD

**Issue by jpecimage** [Davidobot/BetterJoy#537]
**Describe the bug**
I open betterjoy, then plug in my controller. I hear two "connected" pings, then a single disconnect ping and betterjoy force closes. My controller has worked before, the first time I used betterjoy it worked perfectly, but I can't seem to replicate when it works/when it doesn't, it seems to be luck of the draw.

It pops the controller in, sees it, then closes and disconnects. Background doesn't turn green

If I open betterjoy with controller already connected it plays one "connected" ding then disconnects, the program doesn't open.

I've tried it with HIDG installed and uninstalled and it doesnt seem to change anything.

Using 6.4a (have tried earlier versions but have had large lag issues - tried v6.2_fix_input_delay and v6.2_revert...) - v6.2_revert... and betterjoy-200520-2023 sees controller and functions as expected but lag is approx 1s, v6.2_fix_input_delay doesnt recognise controller.

I have seen in a separate post similar but not same issues - that is, throttling the PC, but I'm not experiencing that hence a new thread. One comment on a different issue suggests to compile locally but frankly I don't know what that means and a quick google doesn't shed much light...

**Expected behavior**
I expected the controller to work but it repeatedly disconnects and then closes betterjoy

**Controller (please complete the following information):**
 - Switch Pro
 - USB

**Comment by shukenmg** [comment]
Try using BT to connect.

**Comment by jpecimage** [comment]
Sadly I have no bluetooth card/adapter on my PC so can only use wired at the moment

**Comment by shukenmg** [comment]
Unplug the pro controller and turn it off.
Then try going to control panel > hardware and sound > Devices and printers, check if you see a device named `Pro Controller` if you do right click and remove it. 
When you are sure it's removed try connecting the controller to BetterJoy again.

**Comment by jpecimage** [comment]
Did that just now - controller didnt show up unless plugged in. Plugged in then removed device. Tried again through betterjoy and same issue happened, saw controller then disconnected and closed, and now the controller (plugged in) doesn't show up in devices

**Comment by shukenmg** [comment]
did you try restarting your pc?

**Comment by jpecimage** [comment]
Yep tried it just now. Removed controller, restarted, same thing happened. Betterjoy opened, then I plugged controller in, program detected controller before windows was done "setting up" the controller, then closed immediately (still before windows done setting up controller). I'm pretty stumped tbh, I really appreciate the help

**Comment by jpecimage** [comment]
Just discovered my PC is SUPER out of date (last update was prior to May 2020) so I'm updating now and will report back/close thread if it all works dandy

**Comment by shukenmg** [comment]
@jpecimage Haha, ok

**Comment by jpecimage** [comment]
Alright update didn't fix anything, all problems persist in exactly the same manner as before. Have tried all the troubleshooting above and nothing seems to fix it

**Comment by jpecimage** [comment]
So I updated windows, uninstalled all betterjoy drivers and files, redownloaded/reinstalled the new version from last 24hrs, and everything seems to be working fine so I shall close this thread. thanks for the help!

**Comment by shukenmg** [comment]
Nice
