### ISSUE TITLE
Inaccurate pointer in Dolphin (update: not caused by betterjoy)

### ISSUE THREAD

**Issue by JippC** [Davidobot/BetterJoy#550]
**Describe the bug**
I'm trying to play through Mario Galaxy and I've run into a couple of major issues
1. The cursor seems to be slightly inaccurate, even though it displays fine? For example I'll run the cursor over some starbits, and it won't pick them up. or I'll aim at a spot to shoot at, and it shoots it in a totally other direction
2. I can't grab the blue star here, despite my cursor visably being right over it
![RMGE01_2020-09-24_16-22-55](https://user-images.githubusercontent.com/20575002/94210638-2352f980-fe84-11ea-8444-cb0dbd26c965.png)

**Controller (please complete the following information):**
- Joycons (Im not sure if its split or joind. I'm not using the Joycon grip, I'm using them both seperately to control the game as a wiimote+nunchuck)
- bluetooth connection

I'm pretty much using the default settings as far as motion controls go.

**Comment by SmartDodo1** [comment]
I have been having the same issue

**Comment by JippC** [comment]
> 
> 
> I have been having the same issue on keyboard and mouse

Try turning of MSAA. That did the trick for me
I found this out from a comment on Dolphin's official tracker https://bugs.dolphin-emu.org/issues/12265
Guy was having a similar issue to us.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
please close this issue
