### ISSUE TITLE
[BUG]Duplicate timestamp enqueued starting when low battery notification appears - no steam open

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [Davidobot/BetterJoy#560]
When I get a low battery notification, it takes a lot of screenshots really fast (capture button is set to PrtScrn) and when I look at the log in BetterJoy window, there are a lot of lines that say "Duplicate timestamp enqueued", and in every previous instance I saw this issue talked about (not how it happens, just that it does) you said it was something with steam, which while I have installed, is almost never running

Expected behavior:
no "duplicate timestamp enqueued" lines in the log and no screenshots taken

Happens with ProCon Over Bluetooth, don't know about JoyCons and it can happen with USB if no power is supplied

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
nvm it was something else taking control of it

**Comment by JacobWalrath1** [comment]
Do you know what was taking control of it? Same problem here.

**Comment by traycerb** [comment]
I get this same issue using an 8BitDo Pro2 connected via Bluetooth in Switch mode.  Windows 10 pops up a BetterJoy toast "low battery notification" and BetterJoy ended up with 20,000+ lines of "Duplicate timestamp enqueued" in its log.

![image](https://user-images.githubusercontent.com/4313283/154783125-8157daf1-02c5-4268-bda3-8af42efec053.png)

The first notification did pop up after Steam started, but the behavior persisted even after exiting Steam.

Interestingly, when using the controller with wired USB connection, the "low battery notification" still pops up, but never repeats.  Any ideas what's happening, and why the link to Steam?
