### ISSUE TITLE
[BUG] Can't press ZL and ZR simultanously on the pro controller (using Snes9x)

### ISSUE THREAD

**Issue by Yikarur** [Davidobot/BetterJoy#570]
**Describe the bug**
On Snes9x ZL and ZR are mapped as Z Down and Z Up respectively and for some reason they won't register simultanously. I can press and hold them seperately but as soon as I press the other button (L/R) (using input display to confirm) neither is recognized.

![image](https://user-images.githubusercontent.com/58751053/95781759-c43c1400-0cce-11eb-9eda-3f1fe8a85c92.png)

**Expected behavior**
If a game has a move that requires L and R to be pressed simultanously I should be able to do that with any configuration

**Controller (please complete the following information):**
 - Type: Nintendo Switch Pro Controller
 - Connection: Bluetooth

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
that's an issue exclusive snes9x

**Comment by vaguerant** [comment]
Years later, but is this really a Snes9x issue? The way BetterJoy maps the ZL/ZR buttons is as **Z axis+** and **Z axis-**. Pressing both of these at the same time sets the Z axis to 0, which is identical to pressing neither button. I see the same issue in Project64 when trying to press both buttons simultaneously, and you can even see it in the Windows game controllers dialogue. I'm not sure if this is even possible with BetterJoy.

**Comment by vaguerant** [comment]
Can confirm, switching to a different Project64 input plugin with better XInput handling (N-Rage V2 for me) makes simultaneous ZL/ZR work just fine.
