### ISSUE TITLE
[BUG] Switch Pro Controller Gyro Drift

### ISSUE THREAD

**Issue by SebMan12311** [Davidobot/BetterJoy#576]
**Describe the bug**
My Pro Con Gyro seems to drift slightly right in all my Cemu games. I have cemuhook. I recalibrated the motion controls on a real Switch and the Gyro works fantastically on a real switch, no issues there. However, my controller's gyro still drifts to the right on Cemu. This makes games like Splatoon almost unplayable. Any fixes?

I assume that this is a problem with BetterJoy, if it is a problem with Cemu please tell me and I'll close this.

Edit: It seems to be drifting very slightly in all sorts of directions depending on what direction I'm holding the controller. I tried enabling 'Non-Origional Controller' but it slowed the stick movements and completely disabled the motion controls. Is it possible to get motion controls that work without any drift?

**Controller (please complete the following information):**
 - Type: Pro Con
 - Connection: USB

**Comment by shukenmg** [comment]
Did you calibrate the controller in betterjoy?
The button should show up when you enabled 'Non-Original Controller'.

**Comment by shukenmg** [comment]
Try updating to V6.4b
If that doesn't work you could also try this build that includes #522 and #527 
[TestV2.zip](https://github.com/Davidobot/BetterJoy/files/5434135/TestV2.zip)
I used to have this issue but using this build fixed them.

**Comment by policeman0077** [comment]
> Try updating to V6.4b
> If that doesn't work you could also try this build that includes #522 and #527
> [TestV2.zip](https://github.com/Davidobot/BetterJoy/files/5434135/TestV2.zip)
> I used to have this issue but using this build fixed them.

thanks man , this sovled the gyro drifting problem on my switch pro controller

**Comment by SebMan12311** [comment]
Thank you so much @shukenmg, that calibrate button is really useful and I hope it'll be included in the next update. It fixed almost all of the drift, to the point where it is hard to notice any drift at all. Just a question: do you need to calibrate every time you launch BetterJoy, and if so, is there a way to make the calibration permanent?
Anyway, big well done to you, thanks for this!

**Comment by shukenmg** [comment]
@SebMan12311 
Thank you, I just made the calibrate button more accessible @Davidobot did all the work for calibration.
The calibration data is saved between launches, so there's no need to recalibrate every launch, just recalibrate if any drift occurs.

**Comment by SebMan12311** [comment]
Awesome, thanks! I'll close this now.

**Comment by orckine** [comment]
> Try updating to V6.4b If that doesn't work you could also try this build that includes #522 and #527 [TestV2.zip](https://github.com/Davidobot/BetterJoy/files/5434135/TestV2.zip) I used to have this issue but using this build fixed them.

MAN THIS SAVED ME!
