### ISSUE TITLE
[BUG] Unable to Connect 8bitdo Pro Controller 

### ISSUE THREAD

**Issue by raydiayt** [Davidobot/BetterJoy#635]
(Each step assumes controller is already connected to Windows through bluetooth)

_**Describe the bug**_

_On version 6.4b:_
Controller not instantly recognized/located so I try "Add Controllers" and select the controller (named Xbox Bluetooth Gamepad) and apply "Pro Controller" type. 
At this point, Betterjoy detects the controller upon startup; console says 

"Pro controller connected.
Starting poll thread.
Starting on server 127.0.0.1:26760
All systems go"

and immediately crashes as soon as the window opens.
So I try

- Turning on/off "Nonoriginal Controller"
- Turning on/off HIDGuardian (installed in drivers folder)
- Turning on/off "Purge" options

which all lead to the same result, aside from nonoriginal controller outright not recognizing the controller. This is the same as issue #513 
If I start cemu and betterjoy with the controller off, Betterjoy will connect the controller and start the poll thread but immediately crash as soon as it starts. Someone had this issue in issue #86  but in wired mode, apparently working in bluetooth. 

Trying a different version a la issue 513:
_v6.3_
With purge options and HIDG enabled and/or disabled, the controller is not detected.

_**Expected behavior**_
Expected controller to stay connected in v6.4b, and Betterjoy to not crash upon opening the window/starting poll thread.

Expected controller to at least be detected in v6.3.

**Controller (please complete the following information):**
 - Type: 8bitdo SN30 Pro+ 
 - Connection: Bluetooth 4.0 through USB adapter

**Comment by Dougal19** [comment]
Are you connecting the controller in Switch mode (hold Y, then press Start)? When I do that my PC picks it up as a Switch Pro controller.

**Comment by raydiayt** [comment]
> Are you connecting the controller in Switch mode (hold Y, then press Start)? When I do that my PC picks it up as a Switch Pro controller.

Huh.

I was under the impression it only worked in Windows mode using X. That did it, and motion controls are working great.

Thank you!
