### ISSUE TITLE
Not Displaying

### ISSUE THREAD

**Issue by DubstepUnicorn** [Davidobot/BetterJoy#680]
Whenever I click on the .exe, I doesn't display. Not only that, but if I click it again, it displays a message that "Instance Already Running" eve though I can't see it and therefore use it.

**Comment by slyyyle** [comment]
This is happening to me, but I was simply being impatient.  It takes 2-3 full minutes for BetterJoy to become visible on my computer.  I think many people have been having this same issue, but what I've found is to simply be patient and it will appear.  Same thing for when it appears and I connect a controller.  BetterJoy will become non responsive, but if I wait for a few minutes it comes back and my controller appears in BetterJoy.  FYI, I'm using a nintendo pro controller.
