### ISSUE TITLE
vigemclient.dll module missing after installing drivers

### ISSUE THREAD

**Issue by HarveyAtwal** [Davidobot/BetterJoy#72]
Installed BetterJoyForCemu on a fresh install of Windows 10. Followed instructions and have drivers installed. However, the program crashed the moment it is opened.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.ViGEmClient.vigem_alloc()
   at Nefarius.ViGEm.Client.ViGEmClient..ctor()
   at BetterJoyForCemu.Program.Start()
   at BetterJoyForCemu.MainForm.MainForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
BetterJoyForCemu
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/harvey/Downloads/BetterJoyForCemu_v5_x64%20(1)/BetterJoyForCemu.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
Nefarius.ViGEmClient
    Assembly Version: 1.14.3.0
    Win32 Version: 1.14.3.0
    CodeBase: file:///C:/Users/harvey/Downloads/BetterJoyForCemu_v5_x64%20(1)/Nefarius.ViGEmClient.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by Jarozan** [comment]
I have this problem _exactly._  Also on Windows 10, so I wonder if it's a problem unique to this version of Windows.

**Comment by Gabrieloliveirademoraes** [comment]
ola pessoal.

então, eu estou tentando emular um controle generico atraves do xoutput. o xoutput usa a biblioteca vigem, 

então eu baixei a vigem atravez do powersheel, umas semana funionou, mas otem eu tentei abrir e o xoutput 

não abriu, entao fui olhao o script dele e estava escrito o seguinte

2019-04-26 18:01:32.773 -03:00 INFO  LanguageManager.set_Language: Language is set to English
2019-04-26 18:01:32.776 -03:00 INFO  MainWindowViewModel.Initialize: Loading settings was successful.
2019-04-26 18:01:32.805 -03:00 ERROR MainWindowViewModel.UnhandledException: System.DllNotFoundException: Não é possível carregar a DLL 'vigemclient.dll': Não foi possível encontrar o módulo especificado. (Exceção de HRESULT: 0x8007007E)
   em Nefarius.ViGEm.Client.ViGEmClient.vigem_alloc()
   em Nefarius.ViGEm.Client.ViGEmClient..ctor()
   em XOutput.Devices.XInput.Vigem.VigemDevice.IsAvailable()
   em XOutput.UI.Windows.MainWindowViewModel.Initialize(Action`1 log)
   em XOutput.UI.Windows.MainWindow..ctor(MainWindowViewModel viewModel)
   em XOutput.App.Application_Startup(Object sender, StartupEventArgs e)
   em System.Windows.Application.OnStartup(StartupEventArgs e)
   em System.Windows.Application.<.ctor>b__1_0(Object unused)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
eu tentei reinstalar o a vigem, tentei reinstalar o app, mas não funcionou de jeito maneira, alguem pode me ajudar por favor?
