### ISSUE TITLE
[BUG] Can't connect any devices

### ISSUE THREAD

**Issue by OsoaGitHub** [Davidobot/BetterJoy#727]
**Describe the bug**
I'm trying to connect my 8bitdo SN30Pro+ to BetterJoy, with the Y-Mode on, and HidGuardian, but it just won't connect. Nothing shows up. A Nintendo controller is found in my Windows bluetooth settings, but I am unable to connect to it as it asks for a pin.

**Expected behavior**
The controller should connect to the app easily.

**Controller:**
 - Type: SN30Pro+ (acts like a Pro Controller as far as I know)
 - Connection: Bluetooth

**Comment by DitDitGitHub** [comment]
It works when connected via USB, but motion controls don't so I'm trying to do it via BT

**Comment by DitDitGitHub** [comment]
Ok it doesn't seem to just be affecting my 8bitdo, also my Joycons.

**Comment by DitDitGitHub** [comment]
I've double checked my drivers, all fine
