### ISSUE TITLE
Ability to adjust deadzones?

### ISSUE THREAD

**Issue by sondregronas** [Davidobot/BetterJoy#75]
Is there a way to adjust the deadzones of the WiiU controllers, both inner and outer? For applications other than CEMU. 

Alternatively add ~5% on both ends from the beginning, as the outer edge lacks a bit in the corners compared to a Xbox controller.

Thanks!

**Comment by plxjammerplx** [comment]
Having this issue with Tokyo Mirage FE on Cemu (TOP-RIGHT corner) and then with Alpha Sapphire on Citra (Entire TOP to RIGHT quarter circle). I have tried stick re-calibration, however every other game on Cemu and Citra is functioning properly.
