### ISSUE TITLE
[BUG] Latest version crashes immediately on launch in Windows 7

### ISSUE THREAD

**Issue by sirkris** [Davidobot/BetterJoy#788]
**Describe the bug**
I try to launch BetterJoyForCemu.exe and it immediately crashes with the following data:

 Problem Event Name:	CLR20r3
  Problem Signature 01:	BetterJoyForCemu.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5f946b3b
  Problem Signature 04:	System.Drawing
  Problem Signature 05:	4.8.3761.0
  Problem Signature 06:	5c9c7001
  Problem Signature 07:	602
  Problem Signature 08:	11
  Problem Signature 09:	System.ArgumentException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	d348
  Additional Information 2:	d348d3be431e7f57e00afbb8fc3f37a2
  Additional Information 3:	028e
  Additional Information 4:	028e5f9f3765b18d4ed368b5d6fbd17c

**Expected behavior**
It should run.

**Controller (please complete the following information):**
Single bluetooth left Joy-Con, but like I said, we never get that far because the program won't even start in the first place.  All drivers are installed.  Could this be a GUI regression in Win7 maybe?  I see System.Drawing and System.ArgumentException in there.

**Comment by TmanGamer** [comment]
I believe the same thing happens to me, I open it, It loads into memory and then immediately closes. And if I quickly open it two times it gives the message saying another instance is already running, but it still closes after I click ok.

**Comment by TmanGamer** [comment]
> I believe the same thing happens to me, I open it, It loads into memory and then immediately closes. And if I quickly open it two times it gives the message saying another instance is already running, but it still closes after I click ok.

It looks like it stops here maybe, I hope this gives some help on why it does this. 
![image](https://user-images.githubusercontent.com/34608057/131535356-c2630abf-7f1e-4e2e-9232-bfd53f963a66.png)
