### ISSUE TITLE
[BUG] gyrotojoy not working

### ISSUE THREAD

**Issue by Milkshakeee** [Davidobot/BetterJoy#832]
Whenever I try to use gyro joystick it doesn't seem to work
I used gyrotomouse which works but forces it to switch between mouse and keyboard/controller that causes issues with certain games

I thought I'd be able to use the gyro through the joystick as to not switch between the two inputs

 - Type: Pro controller
 - Connection: USB

**Comment by ShamanCoder** [comment]
As stated in https://github.com/Davidobot/BetterJoy/wiki/App-Settings, gyro joystick is not yet supported. It is a feature that will be implemented in the future.

**Comment by ShamanCoder** [comment]
However, it is possible that you build https://github.com/Davidobot/BetterJoy/commit/d0709ac6ffbf129579a6cf133bed5fa5f846bb52 and enjoy the feature before it is officially released ( shhh, don't tell Davido! ;) ).

**Comment by Milkshakeee** [comment]
Oh oops my bad sorry about that haha, thought it had already been implemented, and don't worry I won't tell ;))
