### ISSUE TITLE
8bitdo sf30Pro blocked on starting poll thread

### ISSUE THREAD

**Issue by Myst3r90** [Davidobot/BetterJoy#86]
Hello,
I try to use a 8bitdo SF30pro gamepad, last firmware 1.29, and BetterforjoyCemu V5 in USB mode without success.
The gamepad is successfully detected, but I'm stuck on "Starting poll thread". After some time, the connection drop. I've already tried to change the port number in the config but issue is still here. Can you help me ?

Starting server on 127.0.0.1:26761
All systems go
Pro controller connected.
Using user stick calibration data.
Using user stick calibration data.
Starting poll thread.

**Comment by Myst3r90** [comment]
Seems to work perfect in BT mode. Only wire connection has the issue

**Comment by cboscarino** [comment]
I've tried both and can confirm that this only happens in USB mode.  BT mode seems to work.  The reason being is that the controller doesn't seem to ever register as connected over usb.  I'm not sure what about the BT connection assigns the controller to stop searching for connections while the USB mode seems to never actually connect and is always searching for a connection.

**Comment by malistaticy** [comment]
wish i found this before i spent an hour uninstalling and reinstalling the drivers lol...
