### ISSUE TITLE
Not working in windows 11

### ISSUE THREAD

**Issue by LavonDvivon** [Davidobot/BetterJoy#868]
I recently updated to windows 11 and since the program didn't work

Its connects and removes the controller over and over and not working

I'm using a regular pro controller connected with the nintendo provided usb cable, windows 11 home version and the latest updated version of BetterJoy

**Comment by dserranoc** [comment]
Hey, I'm having the same problem. Win11 Pro, latest version of BetterJoy and the Pro Controller connects and disconnects over and over. How did you solve it? Thank you!

**Comment by UndertaleFan6** [comment]
Same. I have a new Windows 11, and BetterJoy does not work.

**Comment by AtlasSkyholder** [comment]
Same problem, Windows 11 with BetterJoy 7.1 and the joycons keep connecting and disconnecting. Been using DS4Windows instead, but I also have problems with that one as the left joystick sometimes has the y axis maxed up. I have to start and and disconnect that app a couple of times for that issue to go away.
Wish BetterJoy could resolve it's Windows 11 issue.
