### ISSUE TITLE
Can't use one joy-con as four

### ISSUE THREAD

**Issue by Mathamagic1010** [Davidobot/BetterJoy#904]
I'm not sure if you can but _it would be nice if_ i could use one joy-con as four so it copies the same button inputs and motion controls _i'm just wondering_

**Comment by spacepill0w** [comment]
What do you need this for? I'm no dev but I might be able to point you in the right direction

**Comment by Mathamagic1010** [comment]
i dont need it anymore and found out how to use it for what i wanted but thank you for offering help

**Comment by spacepill0w** [comment]
> i dont need it anymore and found out how to use it for what i wanted but thank you for offering help

Glad to hear it man. Stay safe out there :)
