### ISSUE TITLE
[BUG] Betterjoy won't open

### ISSUE THREAD

**Issue by SamuelLoperaT** [Davidobot/BetterJoy#925]
I try to open betterjoy from the files, it refuses to launch; something curious is that the process is open for about 5 seconds in the task manager, then is marked as "suspended" and killed.

 - Type: Pro Controller
 - Connection: USB

**Comment by SamuelLoperaT** [comment]
Had to reinstall my whole OS to be able to use betterjoy again

**Comment by whyok456** [comment]
hey anyway to fix this without yknow reinstalling my whole os?
