### ISSUE TITLE
An Options Menu

### ISSUE THREAD

**Issue by TeaBagSmileyFace** [Davidobot/BetterJoy#934]
**The Problem:**
There are a lot of nice features people dont know about and ask to add because they are hidden in the .config file that many overlook. And even if you find it, it's just uncomfortable to look through.

**The Solution:**
An easily accessible menu in the app that has all the settings, like the motion server settings, AB button swap, etc.

**Comment by CherenTheCat** [comment]
There already is one, it's the arrow on the right side of the app. Clicking it opens a scrollable options panel.

**Comment by TeaBagSmileyFace** [comment]
Holy christ on the cross thank you. it still should be made more visible though
