### ISSUE TITLE
[BUG]App won't open on windows 11

### ISSUE THREAD

**Issue by ElectricEdison** [Davidobot/BetterJoy#981]
i have installed all of the driver but when i try to open up the actual app it just does not open.

**Comment by PureKey** [comment]
Having the same issue here.
Downloaded 7.1
installed x64 driver
x86 driver wouldn't install
can't open the application at all
windows 11

**Comment by PureKey** [comment]
@ElectricEdison 
It's possible you haven't extracted the files properly.
My brother figured this out for me.
Hope that helps.

**Comment by ElectricEdison** [comment]
@PureKey 
how would I have extracted the files wrong and how can I do it correctly?

**Comment by whyok456** [comment]
hey sorry im experiencing a similar issue and how do i extract the files correctly?

**Comment by ElectricEdison** [comment]
@whyok456 
 right click the file and go to show more options and click troubleshoot compatibility. Then click troubleshot problems and then test the app. 

Hope that works!

**Comment by LiftRift** [comment]
you need to update steam then it will work. it worked for me

**Comment by whyok456** [comment]
how would updating steam help??? well anyways troubleshoot compatibility didn't help but i could delete the vigembus driver and then the app opens again so ill try and see that particular version of vigembus is the problem

**Comment by psycrow117** [comment]
So is there any fix to this? I just installed this app for the first time and this is also happening to me. app running but i cant see the window. its on my taskbar tray icons but I tried clicking/ double clicking/ right clicking and nothing happens. I'm using Windows 11.
